export const claims = [
  "Podporujeme spolupráci, otevřenost a poctivost",
  "Budeme vládnout otevřeně",
  "Zastavíme prorůstání státu oligarchy",
  "Nabízíme čestné a schopné politiky",
  "Nejméně 10 procent rozpočtu na investice",
  "Uvidíte sami, jak dobře stát hospodaří",
  "Veřejnými financemi nebude stát plýtvat",
  "Snížíme korupci alespoň na západní úroveň",
  "Důchody budou důstojné a růst každý rok",
  "Zřídíme státní penzijní fond pro spoření",
  "Dostanete informace o výši svého budoucího důchodu",
  "Stát vám vyjde vstříc díky digizalizaci",
  "Daňové přiznání se vyplní samo",
  "Zdravotní péči k vám dostaneme blíže",
  "Budeme spolu sledovat kvalitu zdravotnictví",
  "Každý rok zvýšíme slevu na poplatníka",
  "Zdaníme montovny a další komerční nemovitosti",
  "V jídelnách budou lokální sezónní potraviny",
  "Žádné dítě nezůstane přes poledne o hladu",
  "Úředníci budou radit, nikoliv prudit",
  "Stojíme nekompromisně za lidskými právy",
  "Budeme spolupracovat s našimi sousedy v EU",
  "Vyjednáme znovu zastaralé mezinárodní dohody",
  "Zdražíme znečišťování a zábor přírody",
  "Odklidíme staré ekologické zátěže",
  "Novými technologiemi proti znečištění",
  "Pošleme úředníky na stáže do zahraničí",
  "Naučíme děti ve škole dobře hospodařit",
  "Soudy si začnou exekutory hlídat",
  "Jeden dlužník, jeden exekutor",
  "Zastavíme korupci v dotacích na sport",
  "Pomůžeme učitelům jít s dobou",
  "Budeme spolu hodnotit, jak plníme program",
  "Investujeme do rychlejšího soudnictví",
  "Postavíme vysokorychlostní železnice",
  "Přesuneme náklad z kamionů na železnici",
  "Budeme EU předsedat sebevědomě",
];

export const generators = [
  { url: "https://source.unsplash.com/800x800", weight: 3 },
  { url: "https://source.unsplash.com/800x800/?czech", weight: 10 },
  { url: "https://source.unsplash.com/800x800/?pirate", weight: 2 },
  { url: "https://source.unsplash.com/800x800/?protest", weight: 2 },
  { url: "https://source.unsplash.com/800x800/?programming", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?hacker", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?nature", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?forest", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?field", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?river", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?road", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?industry", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?mine", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?craft", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?office", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?doctor", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?teacher", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?judge", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?children", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?senior", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?train", weight: 1 },
  { url: "https://source.unsplash.com/800x800/?money", weight: 1 },
];

export default claims;
